<p style="text-align:center">
    <a href="https://skills.network" target="_blank">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/assets/logos/SN_web_lightmode.png" width="200" alt="Skills Network Logo"  />
    </a>
</p>

# **Data Wrangling Lab**

Estimated time needed: **45** minutes

In this lab, you will perform data wrangling tasks to prepare raw data for analysis. Data wrangling involves cleaning, transforming, and organizing data into a structured format suitable for analysis. This lab focuses on tasks like identifying inconsistencies, encoding categorical variables, and feature transformation.

## Objectives

After completing this lab, you will be able to:

- Identify and remove inconsistent data entries.

- Encode categorical variables for analysis.

- Handle missing values using multiple imputation strategies.

- Apply feature scaling and transformation techniques.

#### Intsall the required libraries

In [175]:
!pip install pandas
!pip install matplotlib

Requirement already satisfied: pandas in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.2.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: C:\Users\cubil\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (2.2.1)
Requirement already satisfied: packaging>=20.0 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\cubil\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: C:\Users\cubil\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

## Tasks

#### Step 1: Import the necessary module.

### 1. Load the Dataset

<h5>1.1 Import necessary libraries and load the dataset.</h5>

Ensure the dataset is loaded correctly by displaying the first few rows.

In [176]:
# Import necessary libraries
import pandas as pd
import numpy as np

# Load the Stack Overflow survey data
dataset_url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/n01PQ9pSmiRX6520flujwQ/survey-data.csv"
df = pd.read_csv(dataset_url)

# Display the first few rows
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,...,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,1,I am a developer by profession,Under 18 years old,"Employed, full-time",Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN
2,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,...,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,4,I am learning to code,18-24 years old,"Student, full-time",NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,...,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
4,5,I am a developer by profession,18-24 years old,"Student, full-time",NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,...,NaN,NaN,NaN,NaN,NaN,NaN,Too short,Easy,NaN,NaN

#### 2. Explore the Dataset

<h5>2.1 Summarize the dataset by displaying the column data types, counts, and missing values.</h5>

In [177]:
df_summarize = pd.DataFrame({
    'Column': df.columns,
    'DataType': df.dtypes.values,
    'Unique Values': [df[col].nunique() for col in df.columns],
    'Missing Values': df.isnull().sum().values,
    'Non-Missing Values': df.notnull().sum().values
})
df_summarize.set_index('Column', inplace=True)
df_summarize

,DataType,Unique Values,Missing Values,Non-Missing Values
Column,,,,
ResponseId,int64,65437,0,65437
MainBranch,object,5,0,65437
Age,object,8,0,65437
Employment,object,110,0,65437
RemoteWork,object,3,10631,54806
...,...,...,...,...
JobSatPoints_11,float64,79,35992,29445
SurveyLength,object,3,9255,56182
SurveyEase,object,3,9199,56238
ConvertedCompYearly,float64,6113,42002,23435
JobSat,float64,11,36311,29126

<h5>2.2 Generate basic statistics for numerical columns.</h5>

In [178]:
df.describe()

,ResponseId,CompTotal,WorkExp,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,ConvertedCompYearly,JobSat
count,65437.000000,3.374000e+04,29658.000000,29324.000000,29393.000000,29411.000000,29450.000000,29448.00000,29456.000000,29456.000000,29450.000000,29445.000000,2.343500e+04,29126.000000
mean,32719.000000,2.963841e+145,11.466957,18.581094,7.522140,10.060857,24.343232,22.96522,20.278165,16.169432,10.955713,9.953948,8.615529e+04,6.935041
std,18890.179119,5.444117e+147,9.168709,25.966221,18.422661,21.833836,27.089360,27.01774,26.108110,24.845032,22.906263,21.775652,1.867570e+05,2.088259
min,1.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000e+00,0.000000
25%,16360.000000,6.000000e+04,4.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,3.271200e+04,6.000000
50%,32719.000000,1.100000e+05,9.000000,10.000000,0.000000,0.000000,20.000000,15.00000,10.000000,5.000000,0.000000,0.000000,6.500000e+04,7.000000
75%,49078.000000,2.500000e+05,16.000000,22.000000,5.000000,10.000000,30.000000,30.00000,25.000000,20.000000,10.000000,10.000000,1.079715e+05,8.000000
max,65437.000000,1.000000e+150,50.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,1.625660e+07,10.000000

In [179]:
df.describe(include='object')

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,...,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,SurveyLength,SurveyEase
count,65437,65437,65437,54806,65437,54466,60784,60488,49237,40897,...,27710,28911,28844,28251,27764,28491,28807,28858,56182,56238
unique,5,8,110,3,1,118,8,418,10853,113,...,5,5,5,954,514,3,9,15,3,3
top,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,1-2 times a week,30-60 minutes a day,15-30 minutes a day,None of these,None of these,Hybrid (on-prem and cloud),Traditional public search engine,Software Development,Appropriate in length,Easy
freq,50207,23911,39041,23015,65437,9993,24942,3674,603,6947,...,14426,10951,9341,2364,2834,13230,15813,11918,38767,30071

### 3. Identifying and Removing Inconsistencies

<h5>3.1 Identify inconsistent or irrelevant entries in specific columns (e.g., Country).</h5>

In [180]:
missing_values = df.isnull().sum()  
missing_percentage = (missing_values / len(df)) * 100 

missing_data = pd.DataFrame({
    'Missing Values': missing_values,
    'Percentage': missing_percentage
})
high_missing_data = missing_data[missing_data['Percentage'] > 70]
df.drop(columns=high_missing_data.index, inplace=True)

In [181]:
null_values = df['Country'].isnull().sum()
print("Valores nulos:", null_values)

Valores nulos: 6507

In [182]:
df = df[df['Country'].notnull()]
value_counts = df['Country'].value_counts()
more_than_100 = value_counts[value_counts >= 100]
print(more_than_100.sum())
filtered_df = df[df['Country'].isin(more_than_100.index)]
print(filtered_df)

56097
       ResponseId                      MainBranch                 Age  \
0               1  I am a developer by profession  Under 18 years old
1               2  I am a developer by profession     35-44 years old
2               3  I am a developer by profession     45-54 years old
3               4           I am learning to code     18-24 years old
4               5  I am a developer by profession     18-24 years old
...           ...                             ...                 ...
65413       65414           I am learning to code     18-24 years old
65415       65416     I code primarily as a hobby     35-44 years old
65428       65429  I am a developer by profession     25-34 years old
65431       65432  I am a developer by profession     45-54 years old
65435       65436  I am a developer by profession     18-24 years old

                Employment                            RemoteWork   Check  \
0      Employed, full-time                                Remote  Apples
1      Employed, full-time                                Remote  Apples
2      Employed, full-time                                Remote  Apples
3       Student, full-time                                   NaN  Apples
4       Student, full-time                                   NaN  Apples
...                    ...                                   ...     ...
65413   Student, full-time                                   NaN  Apples
65415  I prefer not to say                                   NaN  Apples
65428  Employed, full-time                                Remote  Apples
65431  Employed, full-time  Hybrid (some remote, some in-person)  Apples
65435  Employed, full-time  Hybrid (some remote, some in-person)  Apples

                                        CodingActivities  \
0                                                  Hobby
1      Hobby;Contribute to open-source projects;Other...
2      Hobby;Contribute to open-source projects;Other...
3                                                    NaN
4                                                    NaN
...                                                  ...
65413                                                NaN
65415                                                NaN
65428  Hobby;Contribute to open-source projects;Profe...
65431  Hobby;Contribute to open-source projects;Profe...
65435  Hobby;Contribute to open-source projects;Profe...

                                                 EdLevel  \
0                              Primary/elementary school
1           Bachelor’s degree (B.A., B.S., B.Eng., etc.)
2        Master’s degree (M.A., M.S., M.Eng., MBA, etc.)
3      Some college/university study without earning ...
4      Secondary school (e.g. American high school, G...
...                                                  ...
65413  Secondary school (e.g. American high school, G...
65415       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65428       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65431       Bachelor’s degree (B.A., B.S., B.Eng., etc.)
65435  Secondary school (e.g. American high school, G...

                                               LearnCode  \
0                                 Books / Physical media
1      Books / Physical media;Colleague;On the job tr...
2      Books / Physical media;Colleague;On the job tr...
3      Other online resources (e.g., videos, blogs, f...
4      Other online resources (e.g., videos, blogs, f...
...                                                  ...
65413  Other online resources (e.g., videos, blogs, f...
65415  Other online resources (e.g., videos, blogs, f...
65428  Books / Physical media;Colleague;Other online ...
65431  Books / Physical media;Colleague;On the job tr...
65435  On the job training;Other online resources (e....

                                         LearnCodeOnline  ... JobSatPoints_6  \
0                                                    NaN  ...            NaN
1      Technical documentation;Blogs;Books;Written Tu...  ...            0.0
2      Technical documentation;Blogs;Books;Written Tu...  ...            NaN
3      Stack Overflow;How-to videos;Interactive tutorial  ...            NaN
4      Technical documentation;Blogs;Written Tutorial...  ...            NaN
...                                                  ...  ...            ...
65413  Social Media;How-to videos;Video-based Online ...  ...            NaN
65415  Blogs;Stack Overflow;Social Media;Video-based ...  ...            NaN
65428  Technical documentation;Books;Interactive tuto...  ...            NaN
65431  Technical documentation;Blogs;Books;Written Tu...  ...            NaN
65435  Technical documentation;Blogs;Written Tutorial...  ...            0.0

      JobSatPoints_7 JobSatPoints_8 JobSatPoints_9 JobSatPoints_10  \
0                NaN            NaN            NaN             NaN
1                0.0            0.0            0.0             0.0
2                NaN            NaN            NaN             NaN
3                NaN            NaN            NaN             NaN
4                NaN            NaN            NaN             NaN
...              ...            ...            ...             ...
65413            NaN            NaN            NaN             NaN
65415            NaN            NaN            NaN             NaN
65428            NaN            NaN            NaN             NaN
65431            NaN            NaN            NaN             NaN
65435            0.0            0.0            0.0             0.0

      JobSatPoints_11           SurveyLength SurveyEase ConvertedCompYearly  \
0                 NaN                    NaN        NaN                 NaN
1                 0.0                    NaN        NaN                 NaN
2                 NaN  Appropriate in length       Easy                 NaN
3                 NaN               Too long       Easy                 NaN
4                 NaN              Too short       Easy                 NaN
...               ...                    ...        ...                 ...
65413             NaN                    NaN        NaN                 NaN
65415             NaN                    NaN        NaN                 NaN
65428             NaN                    NaN        NaN                 NaN
65431             NaN                    NaN        NaN                 NaN
65435             0.0                    NaN        NaN                 NaN

      JobSat
0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
...      ...
65413    NaN
65415    NaN
65428    NaN
65431    NaN
65435    NaN

[56097 rows x 108 columns]

<h5>3.2 Standardize entries in columns 'Employment' by mapping inconsistent values to a consistent format.</h5>

In [183]:
def split_employment(row):
    if isinstance(row, str):         
        parts = row.split(';')
        jobs_times = [p.strip().split(',') for p in parts]
        
        job1, time1, job2, time2 = None, None, None, None
        if len(jobs_times) > 0:
            job1 = jobs_times[0][0].strip()
            time1 = jobs_times[0][1].strip() if len(jobs_times[0]) > 1 else None
        if len(jobs_times) > 1:
            job2 = jobs_times[1][0].strip()
            time2 = jobs_times[1][1].strip() if len(jobs_times[1]) > 1 else None
        
        return pd.Series([job1, time1, job2, time2])
    else:
        return pd.Series([None, None, None, None])

df[['Job1', 'Time1', 'Job2', 'Time2']] = df['Employment'].apply(split_employment)
df=df.drop(columns=['Employment'])
df.head()

,ResponseId,MainBranch,Age,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,...,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat,Job1,Time1,Job2,Time2
0,1,I am a developer by profession,Under 18 years old,Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Employed,full-time,None,None
1,2,I am a developer by profession,35-44 years old,Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,0.0,0.0,NaN,NaN,NaN,NaN,Employed,full-time,None,None
2,3,I am a developer by profession,45-54 years old,Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,NaN,NaN,Appropriate in length,Easy,NaN,NaN,Employed,full-time,None,None
3,4,I am learning to code,18-24 years old,NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,...,NaN,NaN,Too long,Easy,NaN,NaN,Student,full-time,None,None
4,5,I am a developer by profession,18-24 years old,NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,NaN,NaN,Too short,Easy,NaN,NaN,Student,full-time,None,None

### 4. Encoding Categorical Variables

<h5>4.1 Encode the Employment column using one-hot encoding.</h5>

In [184]:
pd.get_dummies(df,columns=['Job1','Time1','Job2','Time2'])

,ResponseId,MainBranch,Age,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,...,Job2_Employed,Job2_Independent contractor,Job2_Not employed,Job2_Retired,Job2_Student,Time2_and not looking for work,Time2_but looking for work,Time2_freelancer,Time2_full-time,Time2_part-time
0,1,I am a developer by profession,Under 18 years old,Remote,Apples,Hobby,Primary/elementary school,Books / Physical media,NaN,NaN,...,False,False,False,False,False,False,False,False,False,False
1,2,I am a developer by profession,35-44 years old,Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,False,False,False,False,False,False,False,False,False,False
2,3,I am a developer by profession,45-54 years old,Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,False,False,False,False,False,False,False,False,False,False
3,4,I am learning to code,18-24 years old,NaN,Apples,NaN,Some college/university study without earning ...,"Other online resources (e.g., videos, blogs, f...",Stack Overflow;How-to videos;Interactive tutorial,NaN,...,False,False,False,False,False,False,False,False,False,False
4,5,I am a developer by profession,18-24 years old,NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65413,65414,I am learning to code,18-24 years old,NaN,Apples,NaN,"Secondary school (e.g. American high school, G...","Other online resources (e.g., videos, blogs, f...",Social Media;How-to videos;Video-based Online ...,NaN,...,False,False,False,False,False,False,False,False,False,False
65415,65416,I code primarily as a hobby,35-44 years old,NaN,Apples,NaN,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Blogs;Stack Overflow;Social Media;Video-based ...,NaN,...,False,False,False,False,False,False,False,False,False,False
65428,65429,I am a developer by profession,25-34 years old,Remote,Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;Other online ...,Technical documentation;Books;Interactive tuto...,API document(s) and/or SDK document(s);User gu...,...,False,False,False,False,False,False,False,False,False,False
65431,65432,I am a developer by profession,45-54 years old,"Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,...,False,False,False,False,False,False,False,False,False,False
65435,65436,I am a developer by profession,18-24 years old,"Hybrid (some remote, some in-person)",Apples,Hobby;Contribute to open-source projects;Profe...,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,...,False,False,False,False,False,False,False,False,False,False

### 5. Handling Missing Values

<h5>5.1 Identify columns with the highest number of missing values.</h5>

In [185]:
missing_values = df.isnull().sum()  
missing_percentage = (missing_values / len(df)) * 100 

missing_data = pd.DataFrame({
    'Missing Values': missing_values,
    'Percentage': missing_percentage
})

missing_data = missing_data.sort_values(by='Missing Values', ascending=False)

missing_data.head(10)

                               Missing Values  Percentage
Time2                                   49077   83.280163
Job2                                    48986   83.125742
EmbeddedHaveWorkedWith                  37248   63.207195
ConvertedCompYearly                     35495   60.232479
AIToolNot interested in Using           35305   59.910063
AINextMore integrated                   35124   59.602919
Knowledge_9                             31295   53.105379
Frequency_3                             31220   52.978110
Knowledge_8                             31172   52.896657
ProfessionalTech                        31166   52.886475

<h5>5.2 Impute missing values in numerical columns (e.g., `ConvertedCompYearly`) with the mean or median.</h5>

In [186]:
df['ConvertedCompYearly'] = df['ConvertedCompYearly'].fillna(df['ConvertedCompYearly'].median())
df['ConvertedCompYearly'].isnull().sum()
df['ConvertedCompYearly'].head()

0    65000.0
1    65000.0
2    65000.0
3    65000.0
4    65000.0
Name: ConvertedCompYearly, dtype: float64

<h5>5.3 Impute missing values in categorical columns (e.g., `RemoteWork`) with the most frequent value.</h5>

In [187]:
df['RemoteWork'] = df['RemoteWork'].fillna(df['RemoteWork'].mode()[0])
df['RemoteWork'].isnull().sum()

np.int64(0)

### 6. Feature Scaling and Transformation

<h5>6.1 Apply Min-Max Scaling to normalize the `ConvertedCompYearly` column.</h5>

In [188]:
df['ConvertedCompYearly_MinMax'] = (df['ConvertedCompYearly'] - df['ConvertedCompYearly'].min()) / (df['ConvertedCompYearly'].max() - df['ConvertedCompYearly'].min())
df['ConvertedCompYearly_MinMax'].head()

0    0.003998
1    0.003998
2    0.003998
3    0.003998
4    0.003998
Name: ConvertedCompYearly_MinMax, dtype: float64

<h5>6.2 Log-transform the ConvertedCompYearly column to reduce skewness.</h5>

In [189]:
df['ConvertedCompYearly_log'] = np.log(df['ConvertedCompYearly'])
df['ConvertedCompYearly_log'].skew()

np.float64(-4.127913296945865)

### 7. Feature Engineering

<h5>7.1 Create a new column `ExperienceLevel` based on the `YearsCodePro` column:</h5>

In [203]:
df.dropna(subset=['YearsCodePro'], inplace=True)

df['YearsCodePro'] = df['YearsCodePro'].replace('Less than 1 year', 0)
df['YearsCodePro'] = df['YearsCodePro'].replace('More than 50 years', 51)

df['YearsCodePro'] = df['YearsCodePro'].astype(float)

def classify_experience(years):
    if years <= 2:
        return 'Junior'
    elif 3 <= years <= 5:
        return 'Mid-Level'
    elif 6 <= years <= 10:
        return 'Senior'
    else:
        return 'Expert'

df['ExperienceLevel'] = df['YearsCodePro'].apply(classify_experience)


df['ExperienceLevel'].head()

1     Expert
2     Expert
6     Senior
9     Expert
11    Expert
Name: ExperienceLevel, dtype: object

### Summary

In this lab, you:

- Explored the dataset to identify inconsistencies and missing values.

- Encoded categorical variables for analysis.

- Handled missing values using imputation techniques.

- Normalized and transformed numerical data to prepare it for analysis.

- Engineered a new feature to enhance data interpretation.

Copyright © IBM Corporation. All rights reserved.